baseURL = 'https://sergiosabillon.github.io/'
languageCode = 'en-us'
title = 'Sergio Sabillon'
theme = 'hugo-coder'

[params]
author="Sergio Sabillon"
info = ["Violinist, Arranger", "Valdosta State University"]
avatarURL = "sergio3.jpg"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/sergio-sabillon-305742373/"

[[params.social]]
name = "Facebook"
icon = "fa fa-2x fa-facebook"
weight = 2
url = "https://www.facebook.com/people/Sergio-Violino/100092505549898/"

[[menu.main]]
name = "Bio"
weight = 1
url = "/about/"

[[menu.main]]
name = "Contact Me"
weight = 1
url = "/contact/"

[[menu.main]]
name = "References"
weight = 1
url = "/references/"

[[menu.main]]
name = "Gallery"
weight = 1
url = "/gallery/"

